workflows:
  android-build:
    name: Android Debug Build
    max_build_duration: 60
    environment:
      vars:
        ANDROID_HOME: /usr/local/android-sdk
      java: 17
    scripts:
      - name: Make gradlew executable
        script: chmod +x gradlew
      - name: Build APK
        script: ./gradlew assembleDebug --stacktrace
    artifacts:
      - app/build/outputs/apk/debug/*.apk
    publishing:
      email:
        recipients:
          - "youremail@example.com"


